### PR TITLE
Mqtt enabled for robotic control 

### PR DESCRIPTION
**Pull request by dschonholtz**
The control panel now has an option to enable Mqtt, then once mqtt is enabled, you can also choose to log that data locally.

### CODE REVIEW

**Comment by dschonholtz** [comment]
I couldn't really see an easy path to a few of those changes with the existing global variables. I decided to take this away from the hacky path that it was currently on and to just throw everything in the class. 
Now everything is defined via the side bar but only a couple of those values are visible right now. 

Next up we will actually make it so editing those values is possible. Then once that is done we will move the console box into the sidebar too.

**Comment by vabarbosa** [comment]
@dschonholtz good progress so far. thanks.
let me know if you need assistance or have any questions

**Comment by dschonholtz** [comment]
@vabarbosa This should put in fixes for most of the outstanding items.

1.  Sig figs to two decimal places
2. Unique id for end points to push to
3. Distance scaling factor and a distance estimation that actually works. (I had flipped my x and y values when building the associated equation initially)
4. 120 degree fov is adjustable now

Things that this doesn't have:
Pushing things to a console in the sidebar instead of the devtools console. 
Applying instant changes when a value in the sidebar is changed.
I was lazy and didn't attach listeners to each of the change events for the mqtt data in the sidebar. Instead, when someone turns mqtt off and on again all of the changes are pushed into the new constructor.

That isn't ideal, but if someone modifies the broker address, endpoint val, or client id then those changes shouldn't propagate through unless the mqtt broker is disconnected first.

If we think that this isn't clear then I could add the listeners in and whenever we get an event suggesting one of those values changes we could disconnect and reconnect mqtt with the new values or something else of that ilk.

Let me know whatchu think.

**Review by vabarbosa — APPROVED** [review]
LGTM!
thank you. really appreciate the updates.

**Pull request merged**
